# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7168d5b0c7282ada66d1f37c3e7eef696feab8436cbbe3afb7501e02715c7b25a2dc378ade6c28fbc67c2b14230f5341d7d6ffaee3408b18239ea2e87e940d68

test:
  secret_key_base: 1184c8ed420a3f5f0718cc13832f0f78b8ca1f24f3afe0b300dd60534b345a3dc1e407788f922d4cebec49d982fec419870b10b477bea10959134a7e1dbad364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
